CREATE TABLE IF NOT EXISTS mpa_ratings (
<<<<<<< HEAD
                                           id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(10) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS films (
                                     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name           VARCHAR(100)  NOT NULL,
=======
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100)  NOT NULL,
>>>>>>> develop
    description    VARCHAR(200),
    release_date   DATE          NOT NULL,
    duration       INT           NOT NULL CHECK (duration > 0),
    mpa_rating_id  BIGINT        NOT NULL REFERENCES mpa_ratings(id)
<<<<<<< HEAD
    );

CREATE TABLE IF NOT EXISTS genres (
                                      id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id  BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS users (
                                     id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email    VARCHAR(100) NOT NULL UNIQUE,
    login    VARCHAR(100) NOT NULL UNIQUE,
    name     VARCHAR(100),
    birthday DATE         NOT NULL
    );

CREATE TABLE IF NOT EXISTS friendships (
                                           id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           user_id   BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
=======
);

CREATE TABLE IF NOT EXISTS genres (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id  BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(100) NOT NULL UNIQUE,
    login    VARCHAR(100) NOT NULL UNIQUE,
    name     VARCHAR(100),
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
>>>>>>> develop
    friend_id BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status    VARCHAR(20) NOT NULL CHECK (status IN ('UNCONFIRMED', 'CONFIRMED')),
    UNIQUE (user_id, friend_id),
    CHECK (user_id <> friend_id)
<<<<<<< HEAD
    );

CREATE TABLE IF NOT EXISTS likes (
                                     film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

CREATE TABLE IF NOT EXISTS directors (
                                         id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(100) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS film_directors (
                                              film_id     BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    director_id BIGINT NOT NULL REFERENCES directors(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
    );

CREATE TABLE IF NOT EXISTS reviews (
                                       review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       content     VARCHAR(500) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    film_id     BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    useful      INT DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS reviews_likes (
                                             review_id BIGINT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_like   BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
    );
=======
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS directors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_directors (
    film_id     BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    director_id BIGINT NOT NULL REFERENCES directors(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);
>>>>>>> develop
